version: "3"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - elasticsearch-kibana

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elasticsearch-kibana

networks:
  elasticsearch-kibana:
